### ISSUE TITLE
Location 제공 API를 SSE로 변경

### ISSUE THREAD

**Issue by hojinida** [MyongjiWay/MyongjiWay-Server#122]
### 📄 Describe

기존 프론트에서 3초마다 한번 씩 호출하던 API를 SSE로 변경합니다.

### ✅ Tasks

- [ ] SSE 엔드포인트 구현
- [ ] API 응답 구조 변경 및 데이터 주기 조정
- [ ] 테스트 및 모니터링
- [ ] 문서화 및 가이드 업데이트
- [ ] 배포 및 배포 후 모니터링
