### ISSUE TITLE
Spring REST Docs를 사용한 API 문서화 가이드 및 예제 추가

### ISSUE THREAD

**Issue by hojinida** [MyongjiWay/MyongjiWay-Server#15]
### 📄 Describe

Spring REST Docs를 사용하여 API 문서화를 작성하는 방법에 대한 가이드를 제공하고, 이를 구현하는 예제로 DocsTestController를 생성합니다.

### ✅ Tasks

- [x] DocsTestController에 GET 및 POST 엔드포인트 정의
1. GET /example (쿼리 매개변수 id 포함)
2. POST /example (요청 본문에 message 포함)

- [x] DocsTestController에 대한 테스트 작성:
1. GET 엔드포인트에 대한 테스트 작성
2. POST 엔드포인트에 대한 테스트 작성
 
- [x] 테스트가 Spring REST Docs 스니펫을 생성하는지 확인

- [x] 문서 검증:
1. 테스트를 실행하여 문서화 스니펫을 생성
2. Asciidoctor 문서를 빌드하고 완전성과 정확성을 검토

### 🙋🏻 More

DocsTestController와 DocsTestCotrollerTest, Test.adoc을 참고해 작성해주세요
