### ISSUE TITLE
CI/CD 파이프라인 구축한다.

### ISSUE THREAD

**Issue by hojinida** [MyongjiWay/MyongjiWay-Server#23]
### 📄 Describe

CI/CD 파이프 라인을 구축합니다. GitAction,  AWS 를 일단 쓴다 가정하고 하겠습니다. 

### ✅ Tasks

- [x] CI 파이프라인 설정 
  - [x] PullRequest시 자동 빌드 트리거 설정
  - [x] Test
  - [x] Klint Test
  - [x] configuration files 작성
- [x] 도커 이미지 빌드 스크립트 작성
  - [x] 공통 빌드 스크립트 작성
- [x] 도커 이미지 레지스트리에 푸시 설정
  - [x] Docker Hub 설정
  - [x] 이미지 태깅 규칙 설정
- [x] CD 파이프라인 설정
  - [x] Docker Hub에 이미지 Push
  - [x] SSH 연결로 이미지 배포

### 🙋🏻 More

추후 cicd 도구는 어떤게 좋을지 회의가 필요하다고 판단됨
Yml 파일 등 설정 파일을 어떻게 관리 할 건지 회의가 필요하다고 판단됨
