### ISSUE TITLE
Logging을 위한 LogBack 설정

### ISSUE THREAD

**Issue by hojinida** [MyongjiWay/MyongjiWay-Server#55]
### 📄 Describe

Logging을 위한 LogBack을 설정합니다.

### ✅ Tasks

- [x] Logback 의존성 추가
- [x] Logback 설정 파일 생성
- [x] 로그 생성 코드 추가
