### ISSUE TITLE
공지사항 리펙토링

### ISSUE THREAD

**Issue by hojinida** [MyongjiWay/MyongjiWay-Server#60]
### 🔨 Describe

Controller Test에서 @AutenticationPricipal 오류를 해결함에 따라 임시로 넣어놨던 User 관련 로직부분 수정.
추가로 작성자와 작성일 데이터도 반환.

### ✅ Tasks

- [x] Controller에서 @AutenticationPrincipal 로 User를 주입받고 정상적으로 동작하도록 리팩토링
- [x] Test 다시 작성
- [x] 작성자 , 작성일 데이터 응답 DTO에 추가
